# https://zenn.dev/iwamasa/articles/12af0153e54e93
# https://ymmooot.dev/articles/17/
# https://docs.aws.amazon.com/ja_jp/AmazonS3/latest/userguide/UsingMetadata.html
# パブリックなバケットを作っているのでアップロードは下記のように可能
# curl -X PUT -T hoge.png -H "x-amz-meta-mymetadata1: foo" -H "x-amz-meta-mymetadata2: bar" http://localhost:9000/default-bucket/任意の値
# ボリュームごと消す際には`docker compose down --volumes`
services:
  minio:
    image: minio/minio:RELEASE.2023-01-06T18-11-18Z
    command: ["server", "/data", "--console-address", ":9090"]
    volumes:
      - "minio:/data"
    environment:
      - MINIO_ROOT_USER=minio_root
      - MINIO_ROOT_PASSWORD=minio_password
    ports:
      - "9000:9000"
      - "9090:9090"
  createbuckets:
    image: minio/mc:RELEASE.2022-12-24T15-21-38Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set my_minio http://minio:9000 minio_root minio_password;
      mc mb --ignore-existing my_minio/default-bucket;
      mc anonymous set public my_minio/default-bucket;
      "
 
volumes:
  minio:
    driver: local